application: sportstables
version: 1
runtime: python
api_version: 1
 
handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: images
  
- url: /javascript
  static_dir: javascript    
  
- url: /admin/.*
  script: admin.py
  login: admin
 
- url: /.*
  script: sportstables.py 
  
builtins:
- datastore_admin: on  
  
admin_console:
  pages:
    - name: Delete users
      url: /admin/

